[project]
name = "backend-python"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "email-validator>=2.3.0",
    "fastapi>=0.128.0",
    "firebase-admin>=7.1.0",
    "google-cloud-aiplatform>=1.133.0",
    "google-cloud-firestore>=2.23.0",
    "google-genai>=1.59.0",
    "google-generativeai>=0.8.6",
    "httpx>=0.28.1",
    "langchain>=1.2.6",
    "langchain-core>=1.2.7",
    "langchain-google-genai>=4.2.0",
    "langchain-google-vertexai>=3.2.1",
    "langgraph>=1.0.6",
    "pillow>=12.1.0",
    "pinecone-client>=6.0.0",
    "pyjwt>=2.10.1",
    "python-dotenv>=1.2.1",
    "uvicorn[standard]>=0.40.0",
]
