[project]
name = "backend-python"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.128.0",
    "firebase-admin>=7.1.0",
    "httpx>=0.28.1",
    "langchain>=1.2.6",
    "langchain-google-vertexai>=3.2.1",
    "langgraph>=1.0.6",
    "pinecone-client>=6.0.0",
    "python-dotenv>=1.2.1",
    "uvicorn[standard]>=0.40.0",
]
